"""Tests for the widened identifier terminals (PREDICATE/CONSTANT/NAME/
VARIABLE/SORT, generated by ``fol/_identifiers.py`` — see that module's
docstring for the design this pins down).

Every expected AST below is hand-computed from the grammar's own rules
(first-character case decides PREDICATE vs. term-valued; a bare NAME token
becomes a ``Constant``; ``const_``/bare-NAME both keep the matched text
verbatim, including any ``c_`` prefix — nothing here is generated from a
loop over the same code under test.

D10 (backward compatibility) is additionally verified OUTSIDE this file, by
a differential run of the FOLIO corpus (``tests/fixtures/folio_fol_strings.
txt``) against the parser as committed at HEAD before this widening: all
1214 lines that already parsed produced byte-identical ``repr()`` ASTs
under the widened grammar, and exactly 46 more lines newly parse — see
CHANGELOG.md's entry for this change. ``TestRegressionD10`` below re-checks
a hand-picked slice of that same guarantee in-suite.
"""

import unicodedata

import pytest

from unicode_fol_kit.fol.msflparser import MSFLParser
from unicode_fol_kit.fol.naming import NamingError, ParsingError
from unicode_fol_kit.fol._fol_nodes import (
    Atom, Variable, Constant, Number, Function, Measure,
    And, Or, Not, Implies, Quantifier,
)
from unicode_fol_kit.fol._msfl_nodes import (
    SortedQuantifier, SortedConstant, Lambda, LambdaVar, Application,
)
from unicode_fol_kit.fol._modal_nodes import Box
from unicode_fol_kit.fol._so_nodes import SecondOrderQuantifier
from unicode_fol_kit.fol import _identifiers

FOL = MSFLParser()


# ---------------------------------------------------------------------------
# Unicode letters — NFC and NFD
# ---------------------------------------------------------------------------

class TestUnicodeLetters:
    def test_nfc_polish_name_parses_as_constant(self):
        """'świątek' as given (NFC, the form almost every editor produces)."""
        text = "LostTo(x, świątek)"
        result = FOL.parse(text)
        assert result == Atom("LostTo", [Variable("x"), Constant("świątek")])

    def test_nfd_polish_name_parses_as_constant(self):
        """The SAME word, NFD-decomposed (ś -> 's' + U+0301 COMBINING ACUTE
        ACCENT, ą -> 'a' + U+0328 COMBINING OGONEK): the combining-mark
        continuation class (see _identifiers.combining_class) is what keeps
        this one identifier instead of a letter followed by a stray mark
        that derails the lexer."""
        nfd_name = unicodedata.normalize("NFD", "świątek")
        assert nfd_name != "świątek", "test is meaningless if NFD == NFC here"
        result = FOL.parse(f"LostTo(x, {nfd_name})")
        # The parsed Constant carries the exact source spelling, uncoerced to
        # any particular normal form — the grammar does not normalise.
        assert result == Atom("LostTo", [Variable("x"), Constant(nfd_name)])


# ---------------------------------------------------------------------------
# Underscore
# ---------------------------------------------------------------------------

class TestUnderscore:
    def test_underscored_constants_parse(self):
        result = FOL.parse("Sibling(dani_Shapiro, family_History)")
        assert result == Atom(
            "Sibling", [Constant("dani_Shapiro"), Constant("family_History")])

    def test_leading_underscore_is_still_rejected(self):
        """The underscore is a CONTINUATION character (position 2+), never
        the first — '_foo' opens with a character no identifier terminal
        accepts as its first."""
        with pytest.raises(NamingError):
            FOL.parse("P(_foo)")

    def test_underscored_predicate_parses(self):
        """PREDICATE carries the underscore too. 0.23.0 shipped this
        asymmetric — underscore in term position only — and that broke
        chem/interop.py, whose kit spelling of a ChemLog predicate capitalises
        only the first character: 17 of the chemical signature's 40 predicates
        spell as Has_bond_to / In_ring_of_size_6 / Net_charge_neutral, i.e. as
        names the kit's own parser refused. See
        test_chem_signature_kit_spellings_parse for the exhaustive check."""
        assert FOL.parse("Family_History(x)") == Atom(
            "Family_History", [Variable("x")])

    def test_leading_underscore_in_predicate_position_is_still_rejected(self):
        """The underscore stays a CONTINUATION character in predicate position
        too: it may not open the token, or the first character would no longer
        carry the predicate/term distinction."""
        with pytest.raises((NamingError, ParsingError)):
            FOL.parse("_Family(x)")


# ---------------------------------------------------------------------------
# Digit-leading identifiers
# ---------------------------------------------------------------------------

class TestDigitLeading:
    def test_digit_leading_identifier_parses_as_constant(self):
        result = FOL.parse("Hosted(beijing, 2008SummerOlympics)")
        assert result == Atom(
            "Hosted", [Constant("beijing"), Constant("2008SummerOlympics")])

    def test_digit_leading_identifier_as_a_function_head(self):
        """Digit-leading is folded into NAME, which — like any NAME — can
        also head a function application, never an atom (PREDICATE alone
        can do that, and PREDICATE never starts with a digit)."""
        result = FOL.parse("P(2008SummerOlympics(x))")
        assert result == Atom(
            "P", [Function("2008SummerOlympics", [Variable("x")])])

    def test_plain_integer_is_still_a_number(self):
        assert FOL.parse("P(2008)") == Atom("P", [Number(2008)])

    def test_decimal_is_still_a_number(self):
        assert FOL.parse("P(2.5)") == Atom("P", [Number(2.5)])


# ---------------------------------------------------------------------------
# Classification: first character decides PREDICATE vs. term-valued
# ---------------------------------------------------------------------------

class TestClassification:
    def test_uppercase_first_is_a_predicate(self):
        assert FOL.parse("Ś(x)") == Atom("Ś", [Variable("x")])

    def test_single_lowercase_letter_is_a_variable(self):
        assert FOL.parse("P(ś)") == Atom("P", [Variable("ś")])

    def test_two_lowercase_letters_is_a_name_and_becomes_a_constant(self):
        assert FOL.parse("P(śa)") == Atom("P", [Constant("śa")])

    def test_caseless_script_identifier_is_term_valued(self):
        """Chinese has no upper/lower distinction, so str.isupper() is False
        for every character in it — every bare identifier from such a
        script is therefore term-valued (NAME, here two caseless letters),
        never eligible to head an atom on its own."""
        assert FOL.parse("P(中文)") == Atom("P", [Constant("中文")])

    def test_digit_leading_classifies_as_constant_not_number(self):
        assert FOL.parse("P(2008SummerOlympics)") == Atom(
            "P", [Constant("2008SummerOlympics")])

    def test_plain_digits_classify_as_number(self):
        assert FOL.parse("P(2008)") == Atom("P", [Number(2008)])

    def test_decimal_digits_classify_as_number(self):
        assert FOL.parse("P(2.5)") == Atom("P", [Number(2.5)])


# ---------------------------------------------------------------------------
# D6 — CONSTANT keeps its priority over the now-overlapping NAME
# ---------------------------------------------------------------------------

class TestConstantPriorityOverName:
    """Before this change, CONSTANT ('c_...'/Greek) and NAME never matched
    the same span: NAME never accepted an underscore. Widening NAME to
    accept '_' makes 'c_alpha' ALSO a full match for NAME's alpha-leading
    form (c -> [lowercase], _alpha -> legal NAME continuation with a second
    letter further on). CONSTANT.3 must still win over NAME.2 — this is the
    single most dangerous seam of the whole change (see fol/_identifiers.py's
    module docstring), so it is checked at the LEXER level (which terminal
    actually matched), not just via the resulting AST — the two terminals'
    transforms happen to produce the identical Constant either way (neither
    strips the 'c_' prefix), so an AST-only check could not tell them apart.
    """

    def test_c_prefixed_ascii_constant_lexes_as_constant(self):
        tokens = list(FOL.parser.lex("c_alpha"))
        assert [t.type for t in tokens] == ["CONSTANT"]

    def test_c_prefixed_ascii_constant_parses_to_the_verbatim_name(self):
        assert FOL.parse("P(c_alpha)") == Atom("P", [Constant("c_alpha")])

    def test_c_prefixed_unicode_constant_lexes_as_constant(self):
        """(D6) 'the c_ form itself may also carry Unicode letters'."""
        tokens = list(FOL.parser.lex("c_świątek"))
        assert [t.type for t in tokens] == ["CONSTANT"]

    def test_c_prefixed_unicode_constant_parses(self):
        assert FOL.parse("P(c_świątek)") == Atom("P", [Constant("c_świątek")])


# ---------------------------------------------------------------------------
# λ, μ, and the Greek CONSTANT alternative are unaffected
# ---------------------------------------------------------------------------

class TestGreekAndOperatorGlyphsUnaffected:
    def test_lambda_still_opens_a_lambda_term(self):
        result = FOL.parse("λx. P(x)")
        assert result == Lambda(LambdaVar("x"), Atom("P", [LambdaVar("x")]))

    def test_mu_still_opens_a_measure_term(self):
        result = FOL.parse("μ(a, b) > μ(c, d)")
        assert result == Atom(">", [
            Measure(Variable("a"), Variable("b")),
            Measure(Variable("c"), Variable("d")),
        ])

    def test_lowercase_greek_alpha_is_still_a_constant_via_the_greek_form(self):
        assert FOL.parse("P(α)") == Atom("P", [Constant("α")])

    def test_lowercase_greek_beta_is_still_a_constant_via_the_greek_form(self):
        assert FOL.parse("P(β)") == Atom("P", [Constant("β")])

    def test_lambda_and_mu_are_excluded_from_the_generated_letter_classes(self):
        assert "λ" not in _identifiers.lowercase_class()
        assert "μ" not in _identifiers.lowercase_class()
        assert "λ" not in _identifiers.uppercase_class()
        assert "μ" not in _identifiers.uppercase_class()

    def test_the_constant_greek_run_is_excluded_from_the_generated_letter_classes(self):
        for ch in "αβγδεζηθικνξοπρστυφχψω":
            assert ch not in _identifiers.lowercase_class(), ch
            assert ch not in _identifiers.uppercase_class(), ch

    def test_lambda_lexes_as_lambda_not_as_an_identifier(self):
        assert [t.type for t in FOL.parser.lex("λ")] == ["LAMBDA"]

    def test_greek_alpha_lexes_as_constant_not_as_a_predicate_or_name(self):
        assert [t.type for t in FOL.parser.lex("α")] == ["CONSTANT"]


# ---------------------------------------------------------------------------
# Round-trip: parse -> to_unicode_str -> parse for each new form
# ---------------------------------------------------------------------------

class TestRoundTrip:
    @pytest.mark.parametrize("text", [
        "LostTo(x, świątek)",
        "Sibling(dani_Shapiro, family_History)",
        "Hosted(beijing, 2008SummerOlympics)",
    ])
    def test_roundtrips(self, text):
        formula = FOL.parse(text)
        rendered = formula.to_unicode_str()
        reparsed = FOL.parse(rendered)
        assert reparsed == formula


# ---------------------------------------------------------------------------
# The widening applies in every mode, not just FOL
# ---------------------------------------------------------------------------

class TestAcrossModes:
    def test_fol_mode(self):
        assert FOL.parse("LostTo(x, świątek)") == Atom(
            "LostTo", [Variable("x"), Constant("świątek")])

    def test_msfol_mode_including_sort(self):
        msfol = MSFLParser(many_sorted=True)
        result = msfol.parse("∀x :Person (P(x) → Q(świątek:Person))")
        assert isinstance(result, SortedQuantifier)
        assert result.variable == Variable("x")
        assert result.sort == "Person"
        assert result.formula == Implies(
            Atom("P", [Variable("x")]),
            Atom("Q", [SortedConstant("świątek", "Person")]),
        )

    def test_msfol_mode_sort_terminal_itself_widens(self):
        """SORT (':' + PREDICATE-shaped name) is unaffected by the
        letter-widening in this particular case (sort names are plain ASCII
        in the corpus), but the underscored/digit-leading CONSTANT it
        annotates must still carry through."""
        msfol = MSFLParser(many_sorted=True)
        result = msfol.parse("P(family_History:Person)")
        assert result == Atom("P", [SortedConstant("family_History", "Person")])

    def test_msfl_mode(self):
        msfl = MSFLParser(many_sorted=True, fuzzy=True)
        result = msfl.parse("P(family_History:Person)")
        assert result == Atom("P", [SortedConstant("family_History", "Person")])

    def test_modal_mode(self):
        modal = MSFLParser(modal=True)
        result = modal.parse("□P(świątek)")
        assert result == Box(Atom("P", [Constant("świątek")]))

    def test_second_order_mode(self):
        so = MSFLParser(second_order=True)
        result = so.parse("∃P (P(świątek))")
        assert result == SecondOrderQuantifier(
            "∃", "P", 1, Atom("P", [Constant("świątek")]))


# ---------------------------------------------------------------------------
# D10 — a hand-picked slice of "every string 0.22.0 accepted still parses to
# the structurally identical AST". The full corpus-level guarantee (1214/1214
# FOLIO lines byte-identical, 46 newly accepted) was checked externally by
# diffing this working tree's parser against the parser committed at HEAD
# before this change, over every FOLIO line — see this file's module
# docstring and CHANGELOG.md.
# ---------------------------------------------------------------------------

class TestRegressionD10:
    def test_plain_ascii_atom(self):
        assert FOL.parse("Human(socrates)") == Atom("Human", [Constant("socrates")])

    def test_conjunction_and_implication(self):
        result = FOL.parse("∀x (Human(x) → Mortal(x)) ∧ Loves(alice, bob)")
        assert result == And(
            Quantifier("∀", Variable("x"), Implies(
                Atom("Human", [Variable("x")]), Atom("Mortal", [Variable("x")]))),
            Atom("Loves", [Constant("alice"), Constant("bob")]),
        )

    def test_negation_and_disjunction(self):
        result = FOL.parse("¬P(x) ∨ Q(x)")
        assert result == Or(Not(Atom("P", [Variable("x")])), Atom("Q", [Variable("x")]))

    def test_function_application(self):
        result = FOL.parse("P(dist(x, y))")
        assert result == Atom("P", [Function("dist", [Variable("x"), Variable("y")])])

    def test_c_form_constant_unchanged(self):
        assert FOL.parse("P(c_alpha)") == Atom("P", [Constant("c_alpha")])

    def test_single_letter_variable_unchanged(self):
        assert FOL.parse("P(x)") == Atom("P", [Variable("x")])

    def test_variable_with_digit_tail_unchanged(self):
        assert FOL.parse("P(x1)") == Atom("P", [Variable("x1")])

    def test_multiletter_ascii_constant_unchanged(self):
        assert FOL.parse("P(socrates)") == Atom("P", [Constant("socrates")])

    def test_arithmetic_comparison_unchanged(self):
        result = FOL.parse("dist(x, y) > z ∧ a1 = b1")
        assert isinstance(result, And)

    def test_lambda_application_unchanged(self):
        result = FOL.parse("(λx. P(x))(a)")
        assert result == Application(
            Lambda(LambdaVar("x"), Atom("P", [LambdaVar("x")])), Variable("a"))

    def test_previously_invalid_digit_leading_argument_now_rejected_case_stays_rejected(self):
        """'1' alone followed by something that is not a legal continuation
        character (no letter after it) is still not a number and not an
        identifier — only 'digits THEN a letter' became legal, not 'digits
        then anything'."""
        with pytest.raises((NamingError, ParsingError)):
            FOL.parse("P(1@)")


# ---------------------------------------------------------------------------
# Regression: the ``fol._identifiers`` lookahead rewrite (splicing small
# fixed-size lookahead atoms into the terminal patterns instead of repeating
# the full ``upper``/``lower`` class bodies at every continuation position,
# to shrink ``terminal_block`` from ~190KB to ~58KB) must not change the
# accepted language — see that module's "differently-spelled pattern for the
# exact same set of strings, never a different one" promise. Two ways it
# quietly did, both caught by an exhaustive per-codepoint scan rather than
# the corpus tests above (the FOLIO corpus and the rest of this file's
# formulas never happen to use these codepoints):
# ---------------------------------------------------------------------------

class TestRegressionLookaheadCeiling:
    """(D-CEILING) ``_letter_atom()``'s ``\\w``-based branch has no ceiling
    of its own — unlike the fully-enumerated ``upper``/``lower`` classes it
    replaces, which never scan past ``_identifiers._MAX_CODEPOINT``
    (0x2FFFF) — so without an explicit ceiling it silently accepted letters
    those classes never could, e.g. CJK Unified Ideograph Extension G
    (U+30000-U+3134A, ``str.isalpha()`` true)."""

    def test_codepoint_past_the_scan_ceiling_is_still_rejected(self):
        ext_g = chr(0x30000)
        assert ext_g.isalpha()  # sanity: genuinely a letter, just past the ceiling
        with pytest.raises(NamingError):
            FOL.parse(f"Q({ext_g})")

    def test_predicate_continuation_past_the_scan_ceiling_is_still_rejected(self):
        ext_g = chr(0x30000)
        with pytest.raises(NamingError):
            FOL.parse(f"A{ext_g}(x)")

    def test_sort_continuation_past_the_scan_ceiling_is_still_rejected(self):
        ext_g = chr(0x30000)
        MS = MSFLParser(many_sorted=True)
        with pytest.raises(NamingError):
            MS.parse(f"∀x :A{ext_g} (P(x))")


class TestRegressionUpperNonalphaContinuation:
    """(D-UPPER-NONALPHA) A continuation position (PREDICATE/SORT/NAME's
    own — position two onward) used to accept ANY codepoint with
    ``str.isupper() == True``, via a literal splice of ``uppercase_class()``
    (built from ``str.isupper()`` alone, no ``isalpha()`` condition). The
    lookahead rewrite's ``\\w``-based LETTER atom instead requires
    ``str.isalpha()``, which is not implied by ``str.isupper()``: Roman
    numerals (U+2160-U+216F, category Nl) and circled/squared Latin
    capitals (e.g. U+24B6, category So) are ``isupper() == True`` and
    ``isalpha() == False``, so they silently stopped being legal
    continuation characters. Fixed by giving LETTER an explicit
    ``upper_nonalpha`` alternative for exactly this sliver."""

    def test_circled_latin_capital_in_predicate_continuation(self):
        circled_a = "Ⓐ"  # CIRCLED LATIN CAPITAL LETTER A
        result = FOL.parse(f"A{circled_a}(x)")
        assert result == Atom(f"A{circled_a}", [Variable("x")])

    def test_roman_numeral_in_name_continuation(self):
        roman_one = "Ⅰ"  # ROMAN NUMERAL ONE
        result = FOL.parse(f"Q(a{roman_one})")
        assert result == Atom("Q", [Constant(f"a{roman_one}")])

    def test_circled_latin_capital_in_sort_continuation(self):
        circled_a = "Ⓐ"
        MS = MSFLParser(many_sorted=True)
        result = MS.parse(f"∀x :A{circled_a} (P(x))")
        assert result == SortedQuantifier(
            "∀", Variable("x"), f"A{circled_a}", Atom("P", [Variable("x")]))


# ---------------------------------------------------------------------------
# The chemical vocabulary, end to end
# ---------------------------------------------------------------------------

class TestChemSignatureIsWritable:
    """The test whose absence let 0.23.0 ship a half-widening.

    ``chem/interop.py`` maps each ChemLog predicate to a kit spelling by
    capitalising the FIRST character only, so ``has_bond_to`` becomes
    ``Has_bond_to``. With the underscore widened for term-valued identifiers
    but NOT for predicates, 17 of the 40 chemical predicates spelled as tokens
    the kit's own parser refused — the chemical vocabulary was unwritable in
    the kit's own surface syntax, and nothing in the suite noticed, because
    every underscore case tested came from FOLIO, where they all sit in term
    position.

    Walking the bridge itself (rather than a hand-picked sample of it) is the
    point: a future predicate added to the signature is covered automatically.
    """

    def test_chem_signature_kit_spellings_parse(self):
        from unicode_fol_kit.chem.interop import KIT_TO_CHEMLOG

        assert KIT_TO_CHEMLOG, "the bridge is empty — the test proves nothing"
        failures = []
        for kit_name in sorted(KIT_TO_CHEMLOG):
            try:
                parsed = FOL.parse(f"{kit_name}(a, b)")
            except (NamingError, ParsingError) as exc:
                failures.append((kit_name, str(exc).splitlines()[0]))
                continue
            # Parsed as an ATOM headed by that exact name — not, say, silently
            # swallowed as a term or truncated at the underscore.
            assert isinstance(parsed, Atom), (kit_name, parsed)
            assert parsed.predicate == kit_name, (kit_name, parsed.predicate)
        assert not failures, f"kit spellings the parser refuses: {failures}"

    def test_underscored_chem_predicate_survives_the_round_trip(self):
        """Hand-checked on one representative: parse → render → parse is
        stable, so a formula over the chemical vocabulary can be written,
        printed, and read back."""
        text = "∃x ∃y (C(x) ∧ Cl(y) ∧ Has_bond_to(x, y))"
        first = FOL.parse(text)
        # ∃x ( ∃y ( (C(x) ∧ Cl(y)) ∧ Has_bond_to(x, y) ) ) — ∧ is left-nested,
        # so the underscored atom is the OUTER conjunction's right operand.
        inner_conjunction = first.formula.formula
        assert inner_conjunction.right == Atom(
            "Has_bond_to", [Variable("x"), Variable("y")])
        assert FOL.parse(first.to_unicode_str()) == first

    def test_bridge_maps_the_underscored_spelling_back_to_chemlog(self):
        """The parser accepting ``Has_bond_to`` is only useful if the bridge
        then renames it to the structure's own ``has_bond_to``; otherwise the
        formula parses and still fails to evaluate."""
        from unicode_fol_kit.chem.interop import to_chemlog_names

        parsed = FOL.parse("Has_bond_to(x, y)")
        assert to_chemlog_names(parsed) == Atom(
            "has_bond_to", [Variable("x"), Variable("y")])
