"""A free variable is a parameter in the first-order intuitionistic Kripke search.

A model is ``(W, ≤, D, V)``: ``D_w ⊆ D_w'`` for ``w ≤ w'`` (increasing domains), and the set
of worlds forcing an atom is up-closed and contains a world only where the atom's individuals
exist. ``w ⊩ ∀x φ`` iff for every ``w' ≥ w`` and every ``d ∈ D_w'``, ``w' ⊩ φ(d)``;
``w ⊩ ∃x φ`` iff some ``d ∈ D_w`` has ``w ⊩ φ(d)``; ``w ⊩ A → B`` iff every ``w' ≥ w`` that
forces ``A`` forces ``B``.

A variable that is free in a formula is a PARAMETER: one unknown individual, the same in every
part of the formula. An assignment gives it an individual that EXISTS AT THE WORLD OF
EVALUATION, and the formula is valid iff it is forced at every world of every model under every
such assignment. Domains increase, so the individual then exists at every later world too: the
submodel generated by the world of evaluation has it in all of its domains, and a formula that
is forced at every world of every model is forced at the root of that submodel. So the
parameter is a rigid individual that belongs to every domain of the model, and nothing is lost
by reading it as a constant. The six problems below are the premise-free implications
``(premises) → conclusion``; each is derived by hand from the clauses above.

1. ``P(x) → P(a)`` is NOT valid. One world, ``D = {d, e}``, ``x`` ↦ ``d``, ``a`` ↦ ``e``,
   ``P`` forced of ``d`` only: ``P(x)`` holds and ``P(a)`` does not.
2. ``P(x) → P(x)`` is valid.
3. ``P(x) → ∃y P(y)`` is valid. A world ``w' ≥ w`` that forces ``P(x)`` has ``x ∈ D_w'``
   (``x`` exists at ``w`` and domains increase), and ``y := x`` witnesses ``∃y P(y)`` there.
4. ``∀y P(y) → P(x)`` is valid. A world ``w' ≥ w`` that forces ``∀y P(y)`` forces ``P(d)`` for
   every ``d ∈ D_w'``, and ``x ∈ D_w'``.
5. ``P(x) → P(a)`` with no premise is NOT valid: row 1 again.
6. ``(P(x) ∧ Q(y)) → ∀z (P(z) ∧ Q(z))`` is NOT valid. One world, ``D = {d, e}``, ``x`` ↦ ``d``,
   ``y`` ↦ ``e``, ``P`` forced of ``d`` only, ``Q`` of ``e`` only: the antecedent holds, and
   ``z := d`` gives ``P(d) ∧ Q(d)``, which fails.

Two more formulas with one free variable: ``∀x P(x) → P(y)`` is row 4 (valid), and
``P(y) → ∃x Q(x)`` is NOT valid (one world, ``D = {d}``, ``y`` ↦ ``d``, ``P`` forced of ``d``,
``Q`` of nothing).

A formula with no quantifier is propositional whatever its terms are: an atom is a letter, a
variable in it stands for itself, and two atoms whose terms differ are two letters. That is
what a parameter allows, because no quantifier-free formula without identity ties two terms
together; rows 1, 2 and 5 are decided by the propositional route and give the same answers.
"""

import pytest

from unicode_logic_kit.atp.lj import int_decide, int_prove
from unicode_logic_kit.atp.logic_backends import IntBackend
from unicode_logic_kit.fol.nodes import (
    And, Atom, Constant, Implies, Not, Number, Or, Quantifier, SortedQuantifier, Variable,
    substitute,
)
from unicode_logic_kit.semantics import intuitionistic
from unicode_logic_kit.semantics.intuitionistic import (
    IntKripkeModel, int_countermodel, int_valid,
)

x, y, z = Variable("x"), Variable("y"), Variable("z")
alpha = Constant("alpha")


def P(term):
    return Atom("P", [term])


def Q(term):
    return Atom("Q", [term])


def forall(var, body):
    return Quantifier("∀", var, body)


def exists(var, body):
    return Quantifier("∃", var, body)


def lem(formula):
    return Or(formula, Not(formula))


def as_constants(formula, *names):
    """``formula`` with each named free variable read as the constant of its name."""
    for name in names:
        formula = substitute(formula, Variable(name), Constant(name))
    return formula


# label, formula, free variables, valid -- the six rows of the module docstring, then the two
# formulas with one free variable
ROWS = [
    ("row 1: P(x) -> P(a)", Implies(P(x), P(alpha)), ("x",), False),
    ("row 2: P(x) -> P(x)", Implies(P(x), P(x)), ("x",), True),
    ("row 3: P(x) -> exists y P(y)", Implies(P(x), exists(y, P(y))), ("x",), True),
    ("row 4: forall y P(y) -> P(x)", Implies(forall(y, P(y)), P(x)), ("x",), True),
    ("row 5: |- P(x) -> P(a)", Implies(P(x), P(alpha)), ("x",), False),
    ("row 6: P(x) & Q(y) -> forall z (P(z) & Q(z))",
     Implies(And(P(x), Q(y)), forall(z, And(P(z), Q(z)))), ("x", "y"), False),
    ("forall x P(x) -> P(y)", Implies(forall(x, P(x)), P(y)), ("y",), True),
    ("P(y) -> exists x Q(x)", Implies(P(y), exists(x, Q(x))), ("y",), False),
]
IDS = [label for label, *_ in ROWS]


@pytest.mark.parametrize("label, formula, free, valid", ROWS, ids=IDS)
def test_int_valid_reads_a_free_variable_as_a_parameter(label, formula, free, valid):
    assert int_valid(formula, max_worlds=3) is valid


@pytest.mark.parametrize("label, formula, free, valid", ROWS, ids=IDS)
def test_countermodel_exists_exactly_for_the_invalid_rows(label, formula, free, valid):
    result = int_countermodel(formula, max_worlds=3)
    assert (result is None) is valid


QUANTIFIED_INVALID = [row for row in ROWS
                      if not row[3] and any(isinstance(n, Quantifier) for n in row[1].walk())]


@pytest.mark.parametrize("label, formula, free, valid", QUANTIFIED_INVALID,
                         ids=[row[0] for row in QUANTIFIED_INVALID])
def test_the_countermodel_of_a_quantified_row_has_the_parameter_in_every_domain(
        label, formula, free, valid):
    model, world = int_countermodel(formula, max_worlds=3)
    assert model.domains is not None
    # the parameter is an individual of every world's domain, under the variable's own name
    for name in free:
        for w, domain in model.domains.items():
            assert name in domain, (name, w, domain)
    # the model really does not force the formula, read with its parameters as constants
    assert model.forces(world, as_constants(formula, *free)) is False


def ground(name, *individuals):
    """The key of the atom ``name(individuals…)`` in a valuation, written as the model writes it."""
    return Atom(name, [Constant(i) for i in individuals]).to_unicode_str()


def test_the_countermodel_of_row_1_built_by_hand_refutes_the_formula():
    # one world, D = {x, alpha} (x ↦ d, alpha ↦ e of the derivation), P forced of x only
    model = IntKripkeModel(upset={0: frozenset({0})},
                           valuation={ground("P", "x"): frozenset({0})},
                           domains={0: frozenset({"x", "alpha"})})
    assert model.forces(0, Implies(P(Constant("x")), P(alpha))) is False
    assert model.forces(0, Implies(P(Constant("x")), P(Constant("x")))) is True


def test_the_countermodel_of_row_6_built_by_hand_refutes_the_formula():
    # one world, D = {x, y}, P forced of x only, Q of y only
    model = IntKripkeModel(upset={0: frozenset({0})},
                           valuation={ground("P", "x"): frozenset({0}),
                                      ground("Q", "y"): frozenset({0})},
                           domains={0: frozenset({"x", "y"})})
    formula = as_constants(Implies(And(P(x), Q(y)), forall(z, And(P(z), Q(z)))), "x", "y")
    assert model.forces(0, formula) is False


def test_an_individual_born_later_is_not_one_the_parameter_can_be():
    # ∀x P(x) → P(y) would fail at the root of a model in which y is born at the second world and
    # has no P there. But the root is no world of evaluation for such a y: an assignment gives y
    # an individual that exists where the formula is evaluated. Every parameter is in every
    # domain of the search, so no such model is searched, and the formula is valid.
    formula = Implies(forall(x, P(x)), P(y))
    assert int_countermodel(formula, max_worlds=3) is None


# --- propositional route: a variable in an atom is a letter that stands for itself ----------

def test_a_quantifier_free_formula_with_a_free_variable_is_decided_as_propositional():
    assert int_valid(Implies(P(x), P(x))) is True
    assert int_valid(Implies(P(x), P(alpha))) is False
    assert int_prove([], Implies(P(x), P(x))) is True
    assert int_prove([], Implies(P(x), P(alpha))) is False
    assert int_decide(Implies(P(x), P(x))) is True
    assert int_decide(Implies(P(x), P(alpha))) is False


def test_the_backend_proves_P_x_from_P_x_and_refutes_P_alpha_from_it():
    backend = IntBackend()
    assert backend.decide(P(x), [P(x)]).status == "proved"
    assert backend.decide(P(alpha), [P(x)]).status == "refuted"


def test_g4ip_and_the_backend_refuse_a_quantified_formula_by_name():
    formula = Implies(forall(y, P(y)), P(x))
    with pytest.raises(NotImplementedError, match="quantified input is out of scope"):
        int_prove([], formula)
    verdict = IntBackend().decide(formula)
    assert verdict.status == "unknown"
    assert verdict.reason == "unsupported"


# --- a hand-derived list of formulas with a free variable ----------------------------------
# Each verdict is derived with the clauses above (and the double negation / excluded middle
# facts of intuitionistic logic), not read off the search.

DERIVED = [
    # P(y) forces ¬¬P(y) at every world: a later world that refutes ¬P(y) would have to refute it
    # from a world forcing P(y), and P(y) is up-closed.
    ("P(y) -> ~~P(y)", Implies(P(y), Not(Not(P(y)))), True),
    # one world w0 ≤ w1, P(y) at w1 only: ¬¬P(y) holds at w0 (every successor sees w1), P(y) does not.
    ("~~P(y) -> P(y)", Implies(Not(Not(P(y))), P(y)), False),
    ("forall x P(x) -> ~~P(y)", Implies(forall(x, P(x)), Not(Not(P(y)))), True),
    # the witness of the conclusion is the parameter itself
    ("(P(y) v ~P(y)) -> exists x (P(x) v ~P(x))",
     Implies(lem(P(y)), exists(x, lem(P(x)))), True),
    # w0 ≤ w1, D_w0 = {d, e}, y ↦ d, P(e) at w0, P(d) at w1 only: at w0 the antecedent holds with
    # x := e, and P(y) ∨ ¬P(y) fails (P(d) is not forced at w0 and ¬P(d) fails because w1 forces it)
    ("exists x (P(x) v ~P(x)) -> (P(y) v ~P(y))",
     Implies(exists(x, lem(P(x))), lem(P(y))), False),
    ("forall x (P(x) v ~P(x)) -> (P(y) v ~P(y))",
     Implies(forall(x, lem(P(x))), lem(P(y))), True),
    ("(forall x P(x) v Q(y)) -> forall x (P(x) v Q(y))",
     Implies(Or(forall(x, P(x)), Q(y)), forall(x, Or(P(x), Q(y)))), True),
    # the constant-domain shift: w0 ≤ w1, D_w0 = {d}, D_w1 = {d, e}, y ↦ d, P(d) at w0, P(e) never,
    # Q(d) at w1 only: the premise holds at w0, ∀x P(x) fails at w0 (w1 has e) and Q(y) fails at w0
    ("forall x (P(x) v Q(y)) -> (forall x P(x) v Q(y))",
     Implies(forall(x, Or(P(x), Q(y))), Or(forall(x, P(x)), Q(y))), False),
    ("exists x P(x) -> ~forall x ~P(x)",
     Implies(exists(x, P(x)), Not(forall(x, Not(P(x))))), True),
    ("P(y) & forall x (P(x) -> Q(x)) -> Q(y)",
     Implies(And(P(y), forall(x, Implies(P(x), Q(x)))), Q(y)), True),
    ("(exists x P(x) -> Q(y)) -> forall x (P(x) -> Q(y))",
     Implies(Implies(exists(x, P(x)), Q(y)), forall(x, Implies(P(x), Q(y)))), True),
    ("forall x (P(x) -> Q(y)) -> (exists x P(x) -> Q(y))",
     Implies(forall(x, Implies(P(x), Q(y))), Implies(exists(x, P(x)), Q(y))), True),
    ("exists x Q(x) -> Q(y)", Implies(exists(x, Q(x)), Q(y)), False),
]


@pytest.mark.parametrize("label, formula, valid", DERIVED, ids=[d[0] for d in DERIVED])
def test_a_derived_formula_with_a_free_variable_has_the_derived_verdict(label, formula, valid):
    # every countermodel derived above has at most two worlds and two individuals
    assert int_valid(formula, max_worlds=2, domain_elements=2) is valid


# --- the free variable and the constant are one individual of the model: refused by name -------

def test_a_free_variable_spelled_like_a_constant_is_refused_by_name():
    formula = Implies(P(Variable("c")), And(P(Constant("c")), exists(y, Q(y))))
    with pytest.raises(NotImplementedError, match="'c'"):
        int_valid(formula)
    with pytest.raises(NotImplementedError, match="'c'"):
        int_countermodel(formula)


def test_a_bound_variable_spelled_like_a_constant_is_not_a_free_variable():
    # the variable x is bound, so there is no parameter named x and no clash
    formula = Implies(forall(x, P(x)), P(Constant("x")))
    assert int_valid(formula, max_worlds=2) is True


# --- numerals and predicates of two arities are not left without a valuation ---------------

def test_a_numeral_in_an_atom_is_a_constant_of_its_value():
    one = Number(1)
    assert int_valid(Implies(forall(x, P(x)), P(one)), max_worlds=2) is True
    assert int_valid(Implies(P(one), exists(x, Q(x))), max_worlds=2) is False


def test_one_and_one_point_zero_are_one_constant():
    # P(1) → (P(1.0) ∨ ∃x Q(x)) is valid exactly when 1 and 1.0 are one constant: with two
    # constants P could hold of the first, not of the second, and Q of nothing.
    formula = Implies(P(Number(1)), Or(P(Number(1.0)), exists(x, Q(x))))
    assert int_valid(formula, max_worlds=2) is True


def test_a_numeral_and_a_constant_spelled_alike_are_refused_by_name():
    formula = And(P(Number(1)), And(P(Constant("1")), exists(x, Q(x))))
    with pytest.raises(NotImplementedError, match="spelled alike"):
        int_valid(formula)


def test_a_predicate_used_at_two_arities_is_two_predicates():
    # P(alpha) → ∃x P(x, x) is not valid: one world, D = {alpha}, the unary P forced of alpha,
    # the binary P forced of nothing.
    formula = Implies(P(alpha), exists(x, Atom("P", [x, x])))
    assert int_valid(formula, max_worlds=2) is False
    model, world = int_countermodel(formula, max_worlds=2)
    assert model.forces(world, formula) is False


def test_a_sorted_quantifier_does_not_make_a_free_variable_a_member_of_the_sort():
    # ∀x:S P(x) → P(y) reads as (∃x S(x)) → (∀x (S(x) → P(x)) → P(y)). One world, D = {y, d}, S and P
    # forced of d only: the sort is non-empty, every S-individual has P, and y has no P.
    formula = Implies(SortedQuantifier("∀", x, "S", P(x)), P(y))
    assert int_valid(formula, max_worlds=2) is False
    model, world = int_countermodel(formula, max_worlds=2)
    assert "y" in model.domains[world]


def test_a_free_variable_that_the_premise_puts_in_the_sort_gets_the_property_of_the_sort():
    # (∀x:S P(x)) ∧ S(y) → P(y) is valid: the quantifier reads ∀x (S(x) → P(x)), and y is an
    # individual of every world's domain with S(y) forced, so P(y) is forced.
    formula = Implies(And(SortedQuantifier("∀", x, "S", P(x)), Atom("S", [y])), P(y))
    assert int_valid(formula, max_worlds=2) is True
    assert int_countermodel(formula, max_worlds=2) is None


def test_a_constant_spelled_like_a_fresh_individual_is_not_merged_with_it():
    # ∃x Q(x) → Q(c) is NOT valid for the constant c named `_e0`: one world, D = {c, d}, Q forced
    # of d only. The search names its extra individuals `_e0`, `_e1`, … and skips the names of
    # the constants, so with one extra individual the model has two elements, not one.
    formula = Implies(exists(x, Q(x)), Q(Constant("_e0")))
    assert int_valid(formula, max_worlds=1, domain_elements=1) is False
    model, world = int_countermodel(formula, max_worlds=1, domain_elements=1)
    assert model.forces(world, formula) is False
    assert len(model.domains[world]) == 2


def test_a_parameter_spelled_like_a_fresh_individual_is_not_merged_with_it():
    formula = Implies(exists(x, Q(x)), Q(Variable("_e0")))
    assert int_valid(formula, max_worlds=1, domain_elements=1) is False
    model, world = int_countermodel(formula, max_worlds=1, domain_elements=1)
    assert len(model.domains[world]) == 2
    assert model.forces(world, as_constants(formula, "_e0")) is False


# --- the bound is a bound: None of int_countermodel is not a proof of validity -------------

PEIRCE_LIKE = Or(Or(Implies(Atom("P", ()), Atom("Q", ())), Implies(Atom("Q", ()), Atom("R", ()))),
                 Implies(Atom("R", ()), Atom("P", ())))


def test_a_propositional_non_theorem_can_have_no_countermodel_at_the_default_bound():
    # (P → Q) ∨ (Q → R) ∨ (R → P) is not valid: a root with three incomparable successors, P, Q
    # and R each forced at exactly one of them (four worlds), refutes it -- at the root every
    # disjunct fails: P → Q at the P-successor, Q → R at the Q-successor, R → P at the R-successor.
    assert int_countermodel(PEIRCE_LIKE) is None            # max_worlds=3: the default bound
    model, world = int_countermodel(PEIRCE_LIKE, max_worlds=4)
    assert model.forces(world, PEIRCE_LIKE) is False
    assert int_valid(PEIRCE_LIKE) is False                  # the calculus decides it
    assert int_decide(PEIRCE_LIKE) is False


def test_the_docstrings_do_not_say_a_missing_countermodel_proves_validity():
    for text in (int_countermodel.__doc__, intuitionistic.__doc__):
        assert "so ``None`` proves validity" not in text
        assert "``None`` proves validity" not in text
    assert "NOT a proof of validity" in intuitionistic.__doc__
    assert "never proves validity" in int_countermodel.__doc__
