from .fol import (
    MSFLParser,
    Node, Variable, Constant, Number, Function,
    Atom, Not, And, Or, Xor, Implies, Iff, Quantifier,
    Count, Measure, Cardinality, Contrast,
    Z3Env,
    node_at, replace_at,
    NamingError, ParsingError,
    Span, UNKNOWN, NodeSpans, Path, SpanMap, SpannedFormula,
    traverse, build_span_map, project_spans,
    SCHEMA_VERSION, serialize, deserialize,
    to_casl_spec, formula_to_casl,
    parse_casl_spec, CaslSpec, CaslImportError,
    repair_tptp_formula, repair_tptp_problem,
    repair_formula, DialectRepairResult,
    parse_prolog_clause, parse_prolog_program, load_prolog,
    simplify_for_checking, count_from_existential_chain, expand_count,
    detect_dialects,
    Signature, PredicateDecl, FunctionDecl, ConstantDecl,
    SortedQuantifier, SortedConstant,
    SortedCount, SortedCardinality,
    Nominal, At,
    Dependence, SlashedExists,
    Tensor, With, OPlus, LinearImplies, OfCourse, One, Top, Zero,
    Product, Under, Over,
    WeakConjunction, WeakDisjunction,
    StrongConjunction, StrongDisjunction,
    LukNegation, LukImplication, LukEquivalence,
    LambdaVar, Lambda, Application,
    Box, Diamond, Knows, Believes, Says, Wants,
    Always, Eventually, Next, Until,
    Historically, Once, Previous, Since,
    Obligatory, Permitted,
    Would, Might,
    Announce, AnnounceDiamond,
    SecondOrderQuantifier,
    free_variables,
    substitute, beta_reduce, ReductionLimitError,
    eta_reduce, beta_eta_normalize,
    resolve_lambda_scope,
    to_fol,
    to_nnf, to_pnf, to_cnf, to_dnf, to_tseitin_cnf, skolemize, is_horn,
    has_lambdas, eliminate_lambdas, beta_reduce_step, reduce_trace,
    unify, apply_subst,
    standard_translation, reduce_announcements,
    latex_to_unicode, parse_latex,
    parse_tptp, parse_tptp_formula, load_tptp, TptpFormula,
    parse_tptp_problem, load_tptp_problem, TptpProblem, TptpHeader,
    parse_prover9, parse_prover9_problem, load_prover9, Prover9Formula,
    sanitize_names, sanitize_all, NameMapping,
    to_english,
    CCGDerivation, reduction_derivation,
    hybrid_is_valid,
    qml_translate, qml_is_valid, qml_equivalent,
    to_thf_modal, to_isabelle_modal, BARCAN, CONVERSE_BARCAN, QML_BRIDGES,
)
from .atp import (
    formulas_are_equivalent, check_logical_entailment,
    check_logical_entailment_vampire,
    is_satisfiable, is_valid, get_model,
    fuzzy_is_satisfiable, fuzzy_is_valid, fuzzy_get_model,
    to_z3_arith, is_satisfiable_arith, is_valid_arith, get_model_arith,
    to_clauses, refute, prove, is_valid_resolution,
    ResolutionStep, ResolutionDerivation, ResolutionCheckResult,
    check_resolution_proof, verify_resolution_proof, render_resolution_proof,
    Proof, Line, Subproof, Justification, ProofResult,
    premise, assume, line, flag, FALSUM,
    check_proof, verify_proof,
    render_fitch, render_latex_fitch,
    Sequent, Derivation, Comprehension, SequentResult,
    sequent, derive, axiom,
    check_sequent_proof, verify_sequent_proof, render_sequent_proof,
    from_z3, parse_smtlib, load_smtlib,
    find_fitch_proof, fitch_prove, is_valid_fitch,
    tableau_closed, is_valid_tableau, prove_tableau, tableau_model,
    prove_tableau_detailed, TableauProof,
    TableauCheckError, check_tableau_proof, check_entailment_tableau_detailed,
    modal_tableau_closed, is_modal_valid, modal_prove, modal_decide, modal_countermodel,
    check_lj_proof, verify_lj_proof, int_prove, int_decide,
    Verdict, BackendUnavailable, ProverBackend,
    register_backend, get_backend, available_backends, default_chain,
    run_backend,
    check_entailment_vampire_detailed,
    extract_szs_status, szs_to_verdict_fields,
    TstpStep, TstpDerivation, parse_tstp_derivation,
    portfolio_prove,
    Cvc5Backend,
    EnumSearchResult, modal_enum_search, modal_enum_countermodel,
    kripke_model_to_dict, kripke_model_from_dict, KripkeEnumBackend,
    to_tptp_ncl, Leo3Backend,
    ill_prove, ill_derivable, check_ill_proof, verify_ill_proof,
    render_ill_proof, ILLSequent, ILLDerivation,
    lambek_prove, lambek_derivable, check_lambek_proof, verify_lambek_proof,
    render_lambek_proof, LambekSequent, LambekDerivation,
    ClingoBackend, MinizincBackend,
)
from .semantics import (
    Structure, term_value, satisfies, models,
    evaluate as fuzzy_evaluate,
    TNorm, get_tnorm, TNORMS,
    KripkeModel, satisfies_modal, models_at, reflexive_transitive_closure,
    kleene_value, DESIGNATED,
    satisfies_so, holds,
    so_find_model, so_find_countermodel, so_is_satisfiable_finite, so_is_valid_finite,
    truth_table, TruthTable, is_tautology, is_contradiction, is_satisfiable_tt,
    find_model, find_countermodel, is_satisfiable_finite, is_valid_finite,
    IntKripkeModel, int_valid, int_countermodel,
    TruthMatrix, matrix_value, matrix_is_valid, matrix_is_satisfiable, matrix_entails,
    K3_MATRIX, LP_MATRIX, FDE_MATRIX, MATRICES,
    FreeModel, free_satisfies, free_holds, NONDENOTING,
    free_find_model, free_countermodel, free_is_valid, free_entails,
    announce, box_announce, diamond_announce,
    CounterfactualModel, cf_satisfies, cf_countermodel, cf_valid, would, might,
    CENTERING_LEVELS, DEFAULT_MAX_WORLDS,
    minimal_models, minimal_entails,
    ActionModel, product_update, public_announcement_action,
    common_knowledge_holds, everybody_knows,
    circumscription_formula, circumscription_entails_so,
    RelevantModel, rel_satisfies, rel_countermodel, rel_valid,
    team_satisfies, team_models, MAX_TEAM_SEARCH,
    dependence_to_eso,
)
from .eval import (
    canonicalize, exact_match,
    validate, is_wellformed, validate_text, ValidationReport,
    formulas_are_identical, match_predicates, formulas_are_matched_identical,
    align_symbols, aligned_exact_match,
    EquivalenceResult, equivalent,
    explain_countermodel, batch_decide,
)
from .hol import (
    find_isabelle, isabelle_available, isabelle_decide_modal, isabelle_decide_fol,
    isabelle_decide_counterfactual, isabelle_decide_relevant,
    check_theory, IsabelleInstall, IsabelleNotAvailable, BuildResult,
    ModalVerdict, FolVerdict, modal_axiom_names,
    modal_faithfulness_theory, intuitionistic_faithfulness_theory,
    conditional_faithfulness_theory, relevant_faithfulness_theory,
    to_isabelle_relevant,
    to_isabelle_ill, ill_derivation_theory,
    to_isabelle_lambek, lambek_derivation_theory,
    to_thf_matrix, to_isabelle_matrix,
    to_thf_matrix_entailment, to_isabelle_matrix_entailment,
)
from . import dl   # the ALC description-logic subpackage (dl.concept_satisfiable, …)
from . import comorphism   # logic-to-logic translation registry (Comorphism, …)
from . import hets  # REST binding to a Dockerized HETS server (HetsClient, …)
from . import drt  # Discourse Representation Theory (DRS, parse_drs, drs_to_fol, …)
from . import prob  # exact probabilistic logic (Nilsson bounds, distribution semantics)
from . import chem  # molecules as finite FOL structures (needs the [chem] extra)
from . import ilp  # structures -> an ILP task, and the learned clause back
from . import api  # the seven-verb facade (api.parse_any / check / prove / …) —
                   # namespaced on purpose: api.prove must not shadow the
                   # resolution prover's top-level `prove`

__version__ = "0.23.0"

__all__ = [
    "MSFLParser",
    "Node", "Variable", "Constant", "Number", "Function",
    "Atom", "Not", "And", "Or", "Xor", "Implies", "Iff", "Quantifier",
    "Count", "Measure", "Cardinality", "Contrast",
    "Z3Env",
    "node_at", "replace_at",
    "NamingError", "ParsingError",
    "Span", "UNKNOWN", "NodeSpans", "Path", "SpanMap", "SpannedFormula",
    "traverse", "build_span_map", "project_spans",
    "SCHEMA_VERSION", "serialize", "deserialize",
    "to_casl_spec", "formula_to_casl",
    "parse_casl_spec", "CaslSpec", "CaslImportError",
    "repair_tptp_formula", "repair_tptp_problem",
    "repair_formula", "DialectRepairResult",
    "parse_prolog_clause", "parse_prolog_program", "load_prolog",
    "simplify_for_checking", "count_from_existential_chain", "expand_count",
    "detect_dialects",
    "Signature", "PredicateDecl", "FunctionDecl", "ConstantDecl",
    "formulas_are_equivalent", "check_logical_entailment",
    "check_logical_entailment_vampire",
    "SortedQuantifier", "SortedConstant",
    "SortedCount", "SortedCardinality",
    "Nominal", "At",
    "Dependence", "SlashedExists",
    "Tensor", "With", "OPlus", "LinearImplies", "OfCourse", "One", "Top", "Zero",
    "Product", "Under", "Over",
    "WeakConjunction", "WeakDisjunction",
    "StrongConjunction", "StrongDisjunction",
    "LukNegation", "LukImplication", "LukEquivalence",
    "LambdaVar", "Lambda", "Application",
    "Box", "Diamond", "Knows", "Believes", "Says", "Wants",
    "Always", "Eventually", "Next", "Until",
    "Historically", "Once", "Previous", "Since",
    "Obligatory", "Permitted",
    "Would", "Might",
    "Announce", "AnnounceDiamond",
    "SecondOrderQuantifier",
    "free_variables",
    "substitute", "beta_reduce", "ReductionLimitError",
    "eta_reduce", "beta_eta_normalize",
    "resolve_lambda_scope",
    "to_fol",
    "to_nnf", "to_pnf", "to_cnf", "to_dnf", "to_tseitin_cnf", "skolemize", "is_horn",
    "has_lambdas", "eliminate_lambdas", "beta_reduce_step", "reduce_trace",
    "unify", "apply_subst",
    "standard_translation", "reduce_announcements",
    "latex_to_unicode", "parse_latex",
    "parse_tptp", "parse_tptp_formula", "load_tptp", "TptpFormula",
    "parse_tptp_problem", "load_tptp_problem", "TptpProblem", "TptpHeader",
    "parse_prover9", "parse_prover9_problem", "load_prover9", "Prover9Formula",
    "sanitize_names", "sanitize_all", "NameMapping",
    "qml_translate", "qml_is_valid", "qml_equivalent",
    "to_thf_modal", "to_isabelle_modal", "BARCAN", "CONVERSE_BARCAN",
    # The cross-family bridge registry for qml_is_valid(..., bridges=[...]). The
    # HOL routes accept the SAME three names from unicode_fol_kit.hol.BRIDGES,
    # which stays subpackage-local (a bare "BRIDGES" is too generic at top level,
    # as with hol's ISABELLE_TACTICS / SYSTEMS).
    "QML_BRIDGES",
    "find_isabelle", "isabelle_available", "isabelle_decide_modal",
    "isabelle_decide_fol", "isabelle_decide_counterfactual",
    "isabelle_decide_relevant", "check_theory",
    "IsabelleInstall", "IsabelleNotAvailable", "BuildResult",
    "ModalVerdict", "FolVerdict", "modal_axiom_names",
    "modal_faithfulness_theory", "intuitionistic_faithfulness_theory",
    "conditional_faithfulness_theory", "relevant_faithfulness_theory",
    "to_isabelle_relevant",
    "to_isabelle_ill", "ill_derivation_theory",
    "to_isabelle_lambek", "lambek_derivation_theory",
    "to_thf_matrix", "to_isabelle_matrix",
    "to_thf_matrix_entailment", "to_isabelle_matrix_entailment",
    "dl",
    "prob",
    "chem",
    "ilp",
    "from_z3", "parse_smtlib", "load_smtlib",
    "find_fitch_proof", "fitch_prove", "is_valid_fitch",
    "tableau_closed", "is_valid_tableau", "prove_tableau", "tableau_model",
    "prove_tableau_detailed", "TableauProof",
    "TableauCheckError", "check_tableau_proof",
    "check_entailment_tableau_detailed",
    "check_lj_proof", "verify_lj_proof", "int_prove", "int_decide",
    "Verdict", "BackendUnavailable", "ProverBackend",
    "register_backend", "get_backend", "available_backends", "default_chain",
    "run_backend",
    "check_entailment_vampire_detailed",
    "extract_szs_status", "szs_to_verdict_fields",
    "TstpStep", "TstpDerivation", "parse_tstp_derivation",
    "portfolio_prove",
    "Cvc5Backend",
    "EnumSearchResult", "modal_enum_search", "modal_enum_countermodel",
    "kripke_model_to_dict", "kripke_model_from_dict", "KripkeEnumBackend",
    "to_tptp_ncl", "Leo3Backend",
    "explain_countermodel", "batch_decide",
    "to_english",
    "CCGDerivation", "reduction_derivation",
    "truth_table", "TruthTable", "is_tautology", "is_contradiction", "is_satisfiable_tt",
    "find_model", "find_countermodel", "is_satisfiable_finite", "is_valid_finite",
    "IntKripkeModel", "int_valid", "int_countermodel",
    "TruthMatrix", "matrix_value", "matrix_is_valid", "matrix_is_satisfiable",
    "matrix_entails", "K3_MATRIX", "LP_MATRIX", "FDE_MATRIX", "MATRICES",
    "FreeModel", "free_satisfies", "free_holds", "NONDENOTING",
    "free_find_model", "free_countermodel", "free_is_valid", "free_entails",
    "announce", "box_announce", "diamond_announce",
    "CounterfactualModel", "cf_satisfies", "cf_countermodel", "cf_valid",
    "would", "might", "CENTERING_LEVELS", "DEFAULT_MAX_WORLDS",
    "minimal_models", "minimal_entails",
    "ActionModel", "product_update", "public_announcement_action",
    "common_knowledge_holds", "everybody_knows",
    "circumscription_formula", "circumscription_entails_so",
    "RelevantModel", "rel_satisfies", "rel_countermodel", "rel_valid",
    "team_satisfies", "team_models", "MAX_TEAM_SEARCH",
    "dependence_to_eso",
    "hybrid_is_valid",
    "ill_prove", "ill_derivable", "check_ill_proof", "verify_ill_proof",
    "render_ill_proof", "ILLSequent", "ILLDerivation",
    "lambek_prove", "lambek_derivable", "check_lambek_proof",
    "verify_lambek_proof", "render_lambek_proof", "LambekSequent",
    "LambekDerivation",
    "ClingoBackend", "MinizincBackend",
    "is_satisfiable", "is_valid", "get_model",
    "fuzzy_is_satisfiable", "fuzzy_is_valid", "fuzzy_get_model",
    "to_z3_arith", "is_satisfiable_arith", "is_valid_arith", "get_model_arith",
    "to_clauses", "refute", "prove", "is_valid_resolution",
    "ResolutionStep", "ResolutionDerivation", "ResolutionCheckResult",
    "check_resolution_proof", "verify_resolution_proof", "render_resolution_proof",
    "Proof", "Line", "Subproof", "Justification", "ProofResult",
    "premise", "assume", "line", "flag", "FALSUM",
    "check_proof", "verify_proof",
    "render_fitch", "render_latex_fitch",
    "Sequent", "Derivation", "Comprehension", "SequentResult",
    "sequent", "derive", "axiom",
    "check_sequent_proof", "verify_sequent_proof", "render_sequent_proof",
    "Structure", "term_value", "satisfies", "models", "fuzzy_evaluate",
    "TNorm", "get_tnorm", "TNORMS",
    "KripkeModel", "satisfies_modal", "models_at", "reflexive_transitive_closure",
    "kleene_value", "DESIGNATED",
    "satisfies_so", "holds",
    "so_find_model", "so_find_countermodel",
    "so_is_satisfiable_finite", "so_is_valid_finite",
    "canonicalize", "exact_match",
    "validate", "is_wellformed", "validate_text", "ValidationReport",
    "formulas_are_identical", "match_predicates", "formulas_are_matched_identical",
    "align_symbols", "aligned_exact_match",
    "EquivalenceResult", "equivalent",
]
