from .fol import (
    MSFLParser,
    Node, Variable, Constant, Number, Function,
    Atom, Not, And, Or, Xor, Implies, Iff, Quantifier,
    Count, Measure, Cardinality, Contrast,
    Z3Env,
    NamingError, ParsingError,
    SortedQuantifier, SortedConstant,
    SortedCount, SortedCardinality,
    Nominal, At,
    Dependence, SlashedExists,
    Tensor, With, OPlus, LinearImplies, OfCourse, One,
    Product, Under, Over,
    WeakConjunction, WeakDisjunction,
    StrongConjunction, StrongDisjunction,
    LukNegation, LukImplication, LukEquivalence,
    LambdaVar, Lambda, Application,
    Box, Diamond, Knows, Believes, Says, Wants,
    Always, Eventually, Next, Until,
    Historically, Once, Previous, Since,
    Obligatory, Permitted,
    SecondOrderQuantifier,
    free_variables,
    substitute, beta_reduce, ReductionLimitError,
    eta_reduce, beta_eta_normalize,
    resolve_lambda_scope,
    to_fol,
    to_nnf, to_pnf, to_cnf, to_dnf, to_tseitin_cnf, skolemize, is_horn,
    has_lambdas, eliminate_lambdas, beta_reduce_step, reduce_trace,
    unify, apply_subst,
    standard_translation,
    latex_to_unicode, parse_latex,
    parse_tptp, parse_tptp_formula, load_tptp, TptpFormula,
    parse_prover9, parse_prover9_problem, load_prover9, Prover9Formula,
    sanitize_names, sanitize_all, NameMapping,
    to_english,
    hybrid_is_valid,
    qml_translate, qml_is_valid, qml_equivalent,
    to_thf_modal, to_isabelle_modal, BARCAN, CONVERSE_BARCAN,
)
from .atp import (
    formulas_are_equivalent, check_logical_entailment,
    check_logical_entailment_vampire,
    is_satisfiable, is_valid, get_model,
    fuzzy_is_satisfiable, fuzzy_is_valid, fuzzy_get_model,
    to_z3_arith, is_satisfiable_arith, is_valid_arith, get_model_arith,
    to_clauses, refute, prove, is_valid_resolution,
    Proof, Line, Subproof, Justification, ProofResult,
    premise, assume, line, flag, FALSUM,
    check_proof, verify_proof,
    render_fitch, render_latex_fitch,
    Sequent, Derivation, Comprehension, SequentResult,
    sequent, derive, axiom,
    check_sequent_proof, verify_sequent_proof, render_sequent_proof,
    from_z3, parse_smtlib, load_smtlib,
    find_fitch_proof, fitch_prove, is_valid_fitch,
    tableau_closed, is_valid_tableau, prove_tableau, tableau_model,
    modal_tableau_closed, is_modal_valid, modal_prove, modal_decide, modal_countermodel,
    check_lj_proof, verify_lj_proof,
    ill_prove, ill_derivable, check_ill_proof, verify_ill_proof,
    render_ill_proof, ILLSequent, ILLDerivation,
    lambek_prove, lambek_derivable, check_lambek_proof, verify_lambek_proof,
    render_lambek_proof, LambekSequent, LambekDerivation,
)
from .semantics import (
    Structure, term_value, satisfies, models,
    evaluate as fuzzy_evaluate,
    TNorm, get_tnorm, TNORMS,
    KripkeModel, satisfies_modal, models_at, reflexive_transitive_closure,
    kleene_value, DESIGNATED,
    satisfies_so, holds,
    so_find_model, so_find_countermodel, so_is_satisfiable_finite, so_is_valid_finite,
    truth_table, TruthTable, is_tautology, is_contradiction, is_satisfiable_tt,
    find_model, find_countermodel, is_satisfiable_finite, is_valid_finite,
    IntKripkeModel, int_valid, int_countermodel,
    TruthMatrix, matrix_value, matrix_is_valid, matrix_is_satisfiable, matrix_entails,
    K3_MATRIX, LP_MATRIX, FDE_MATRIX, MATRICES,
    FreeModel, free_satisfies, free_holds, NONDENOTING,
    announce, box_announce, diamond_announce,
    CounterfactualModel, would, might,
    minimal_models, minimal_entails,
    RelevantModel, rel_satisfies, rel_countermodel, rel_valid,
    team_satisfies, team_models, MAX_TEAM_SEARCH,
)
from .eval import (
    canonicalize, exact_match,
    validate, is_wellformed, validate_text, ValidationReport,
    formulas_are_identical, match_predicates, formulas_are_matched_identical,
)
from .hol import (
    find_isabelle, isabelle_available, isabelle_decide_modal, isabelle_decide_fol,
    check_theory, IsabelleInstall, IsabelleNotAvailable, BuildResult,
    ModalVerdict, FolVerdict, modal_axiom_names,
    modal_faithfulness_theory, intuitionistic_faithfulness_theory,
    conditional_faithfulness_theory, relevant_faithfulness_theory,
)
from . import dl   # the ALC description-logic subpackage (dl.concept_satisfiable, …)

__version__ = "0.13.1"

__all__ = [
    "MSFLParser",
    "Node", "Variable", "Constant", "Number", "Function",
    "Atom", "Not", "And", "Or", "Xor", "Implies", "Iff", "Quantifier",
    "Count", "Measure", "Cardinality", "Contrast",
    "Z3Env",
    "NamingError", "ParsingError",
    "formulas_are_equivalent", "check_logical_entailment",
    "check_logical_entailment_vampire",
    "SortedQuantifier", "SortedConstant",
    "SortedCount", "SortedCardinality",
    "Nominal", "At",
    "Dependence", "SlashedExists",
    "Tensor", "With", "OPlus", "LinearImplies", "OfCourse", "One",
    "Product", "Under", "Over",
    "WeakConjunction", "WeakDisjunction",
    "StrongConjunction", "StrongDisjunction",
    "LukNegation", "LukImplication", "LukEquivalence",
    "LambdaVar", "Lambda", "Application",
    "Box", "Diamond", "Knows", "Believes", "Says", "Wants",
    "Always", "Eventually", "Next", "Until",
    "Historically", "Once", "Previous", "Since",
    "Obligatory", "Permitted",
    "SecondOrderQuantifier",
    "free_variables",
    "substitute", "beta_reduce", "ReductionLimitError",
    "eta_reduce", "beta_eta_normalize",
    "resolve_lambda_scope",
    "to_fol",
    "to_nnf", "to_pnf", "to_cnf", "to_dnf", "to_tseitin_cnf", "skolemize", "is_horn",
    "has_lambdas", "eliminate_lambdas", "beta_reduce_step", "reduce_trace",
    "unify", "apply_subst",
    "standard_translation",
    "latex_to_unicode", "parse_latex",
    "parse_tptp", "parse_tptp_formula", "load_tptp", "TptpFormula",
    "parse_prover9", "parse_prover9_problem", "load_prover9", "Prover9Formula",
    "sanitize_names", "sanitize_all", "NameMapping",
    "qml_translate", "qml_is_valid", "qml_equivalent",
    "to_thf_modal", "to_isabelle_modal", "BARCAN", "CONVERSE_BARCAN",
    "find_isabelle", "isabelle_available", "isabelle_decide_modal",
    "isabelle_decide_fol", "check_theory",
    "IsabelleInstall", "IsabelleNotAvailable", "BuildResult",
    "ModalVerdict", "FolVerdict", "modal_axiom_names",
    "modal_faithfulness_theory", "intuitionistic_faithfulness_theory",
    "conditional_faithfulness_theory", "relevant_faithfulness_theory",
    "dl",
    "from_z3", "parse_smtlib", "load_smtlib",
    "find_fitch_proof", "fitch_prove", "is_valid_fitch",
    "tableau_closed", "is_valid_tableau", "prove_tableau", "tableau_model",
    "check_lj_proof", "verify_lj_proof",
    "to_english",
    "truth_table", "TruthTable", "is_tautology", "is_contradiction", "is_satisfiable_tt",
    "find_model", "find_countermodel", "is_satisfiable_finite", "is_valid_finite",
    "IntKripkeModel", "int_valid", "int_countermodel",
    "TruthMatrix", "matrix_value", "matrix_is_valid", "matrix_is_satisfiable",
    "matrix_entails", "K3_MATRIX", "LP_MATRIX", "FDE_MATRIX", "MATRICES",
    "FreeModel", "free_satisfies", "free_holds", "NONDENOTING",
    "announce", "box_announce", "diamond_announce",
    "CounterfactualModel", "would", "might",
    "minimal_models", "minimal_entails",
    "RelevantModel", "rel_satisfies", "rel_countermodel", "rel_valid",
    "team_satisfies", "team_models", "MAX_TEAM_SEARCH",
    "hybrid_is_valid",
    "ill_prove", "ill_derivable", "check_ill_proof", "verify_ill_proof",
    "render_ill_proof", "ILLSequent", "ILLDerivation",
    "lambek_prove", "lambek_derivable", "check_lambek_proof",
    "verify_lambek_proof", "render_lambek_proof", "LambekSequent",
    "LambekDerivation",
    "is_satisfiable", "is_valid", "get_model",
    "fuzzy_is_satisfiable", "fuzzy_is_valid", "fuzzy_get_model",
    "to_z3_arith", "is_satisfiable_arith", "is_valid_arith", "get_model_arith",
    "to_clauses", "refute", "prove", "is_valid_resolution",
    "Proof", "Line", "Subproof", "Justification", "ProofResult",
    "premise", "assume", "line", "flag", "FALSUM",
    "check_proof", "verify_proof",
    "render_fitch", "render_latex_fitch",
    "Sequent", "Derivation", "Comprehension", "SequentResult",
    "sequent", "derive", "axiom",
    "check_sequent_proof", "verify_sequent_proof", "render_sequent_proof",
    "Structure", "term_value", "satisfies", "models", "fuzzy_evaluate",
    "TNorm", "get_tnorm", "TNORMS",
    "KripkeModel", "satisfies_modal", "models_at", "reflexive_transitive_closure",
    "kleene_value", "DESIGNATED",
    "satisfies_so", "holds",
    "so_find_model", "so_find_countermodel",
    "so_is_satisfiable_finite", "so_is_valid_finite",
    "canonicalize", "exact_match",
    "validate", "is_wellformed", "validate_text", "ValidationReport",
    "formulas_are_identical", "match_predicates", "formulas_are_matched_identical",
]
