%import .terminals (PREDICATE, CONSTANT, NAME, VARIABLE, NUMBER, SORT, FORALL, EXISTS, LAMBDA)
%import common.WS

?start: formula

?formula: luk_biimplication
    | lambda_
    | application_

?luk_biimplication: luk_implication
    | luk_implication "↔" luk_biimplication     -> luk_iff_

?luk_implication: same_level_ops
    | same_level_ops "→" luk_implication        -> luk_implies_

?same_level_ops: only_weak_and | only_weak_or | only_strong_and | only_strong_or | luk_negation

?only_weak_and:   luk_negation ("∧" luk_negation)+  -> weak_and_

?only_weak_or:    luk_negation ("∨" luk_negation)+  -> weak_or_

?only_strong_and: luk_negation ("⊗" luk_negation)+  -> strong_and_

?only_strong_or:  luk_negation ("⊕" luk_negation)+  -> strong_or_

?luk_negation: "¬" luk_negation                     -> luk_not_
    | quantifier
    | atom
    | "(" formula ")"
    | "[" formula "]"

?quantifier: (FORALL | EXISTS) VARIABLE SORT luk_negation   -> sorted_quantifier_

?atom: infix_predicate
     | PREDICATE "(" termlist ")"           -> atom_
     | PREDICATE                            -> atom0_

?infix_predicate: term "<"  term            -> lt_
                | term ">"  term            -> gt_
                | term "="  term            -> eq_
                | term "≤" term            -> le_
                | term "≥" term            -> ge_
                | term "≠" term            -> ne_

?termlist: term ("," term)*

?term: sum

?sum: product
    | sum "+" product                       -> add_
    | sum "-" product                       -> sub_

?product: atom_term
    | product "*" atom_term                 -> mul_
    | product "/" atom_term                 -> div_

?atom_term: VARIABLE
    | NAME "(" termlist ")"                 -> function_
    | NAME SORT                             -> sorted_const_
    | CONSTANT SORT                         -> sorted_const_
    | NUMBER                                -> number_
    | "(" term ")"

lambda_: LAMBDA (VARIABLE | NAME | PREDICATE) "." formula
?app_arg: formula | atom_term
application_: "(" formula ")" "(" app_arg ")"

%ignore WS
