%import .terminals (PREDICATE, CONSTANT, NAME, VARIABLE, NUMBER, SORT, FORALL, EXISTS, LAMBDA)
%import common.WS

?start: formula

?formula: biimplication
    | lambda_
    | application_

?biimplication: implication
    | implication "↔" biimplication         -> iff_

?implication: same_level_ops
    | same_level_ops "→" implication        -> implies_

?same_level_ops: only_and | only_or | negation

?only_and: negation ("∧" negation)+         -> and_

?only_or:  negation ("∨" negation)+         -> or_

?negation: "¬" negation                     -> not_
    | quantifier
    | atom
    | "(" formula ")"
    | "[" formula "]"

?quantifier: (FORALL | EXISTS) VARIABLE SORT negation   -> sorted_quantifier_

?atom: infix_predicate
     | PREDICATE "(" termlist ")"           -> atom_
     | PREDICATE                            -> atom0_

?infix_predicate: term "<"  term            -> lt_
                | term ">"  term            -> gt_
                | term "="  term            -> eq_
                | term "≤" term            -> le_
                | term "≥" term            -> ge_
                | term "≠" term            -> ne_

?termlist: term ("," term)*

?term: sum

?sum: product
    | sum "+" product                       -> add_
    | sum "-" product                       -> sub_

?product: atom_term
    | product "*" atom_term                 -> mul_
    | product "/" atom_term                 -> div_

?atom_term: VARIABLE
    | NAME "(" termlist ")"                 -> function_
    | NAME SORT                             -> sorted_const_
    | CONSTANT SORT                         -> sorted_const_
    | NUMBER                                -> number_
    | "(" term ")"

lambda_: LAMBDA (VARIABLE | NAME | PREDICATE) "." formula
?app_arg: formula | atom_term
application_: "(" formula ")" "(" app_arg ")"

%ignore WS
